# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Webscrapers',
                'doc_host': 'https://Dmaturana81.github.io',
                'git_url': 'https://github.com/Dmaturana81/Webscrapers',
                'lib_path': 'Webscrapers'},
  'syms': {'Webscrapers.core': {'Webscrapers.core.foo': ('core.html#foo', 'Webscrapers/core.py')}}}
